In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("customer_purchase.csv")
df.head()

   CustomerID  Age  Income Gender  WebsiteVisitor Purchase
0           1   58   49184      M              48      Yes
1           2   35   84196      M               9       No
2           3   65   46868      M              38      Yes
3           4   45   28331      M               6       No
4           5   31   80990      M              36      Yes

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df['Purchase']=le.fit_transform(df['Purchase'])

In [9]:
x=df[['CustomerID','Age','Income','Gender','WebsiteVisitor']]
y=df[['Purchase']]
x

     CustomerID  Age  Income  Gender  WebsiteVisitor
0             1   58   49184       1              48
1             2   35   84196       1               9
2             3   65   46868       1              38
3             4   45   28331       1               6
4             5   31   80990       1              36
..          ...  ...     ...     ...             ...
995         996   59   79135       1              29
996         997   22   28758       0               2
997         998   38   88453       1               5
998         999   39   64592       0              11
999        1000   64   39661       1              22

[1000 rows x 5 columns]

In [10]:
x=df6[['CustomerID','Age','Income','Gender','WebsiteVisitor']]
y=df[['Purchase']]
y

     Purchase
0           1
1           0
2           1
3           0
4           1
..        ...
995         1
996         0
997         0
998         0
999         0

[1000 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train,x_test,y_train,y_test

(     CustomerID  Age  Income  Gender  WebsiteVisitor
 55           56   58   35433       1               5
 802         803   29  102465       0              40
 299         300   61   32856       0              19
 641         642   21   38092       0               3
 414         415   22  188995       1              40
 ..          ...  ...     ...     ...             ...
 223         224   65   46013       1              41
 216         217   54  185005       1              10
 784         785   58  192309       0              26
 806         807   61  148902       0              46
 337         338   25  193292       1               9

 [700 rows x 5 columns],
      CustomerID  Age  Income  Gender  WebsiteVisitor
 96           97   49   85829       1               6
 69           70   48   76032       0               4
 812         813   25   90225       0              35
 360         361   21  173738       0              43
 398         399   55  124975       1              26
 ..          ...  ...     ...     ...             ...
 218         219   33   51051       0              39
 27           28   47   57452       0               9
 530         531   59   64206       1              11
 310         311   47   39739       1              49
 771         772   41  122533       0              50

 [300 rows x 5 columns],
      Purchase
 55          0
 802         1
 299         0
 641         0
 414         1
 ..        ...
 223         1
 216         1
 784         1
 806         1
 337         1

 [700 rows x 1 columns],
      Purchase
 96          0
 69          0
 812         1
 360         1
 398         1
 ..        ...
 218         1
 27          0
 530         0
 310         1
 771         1

 [300 rows x 1 columns])

In [15]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100,criterion='gini')
model.fit(x_train,y_train)
RandomForestClassifier(random_state=0)

C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier(random_state=0)

In [16]:
model.predict(x_test)

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [17]:
model.score(x_test,y_test)

0.9666666666666667